import type { Metadata } from "next";
import { IM_Fell_Double_Pica } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const imFellDoublePica = IM_Fell_Double_Pica({
  variable: "--font-im-fell-double-pica",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${imFellDoublePica.variable} antialiased`}>
        <header className="w-full bg-background/80 backdrop-blur-sm border-b border-border sticky top-0 z-50">
          <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="text-xl font-semibold text-foreground">
              Lenscape
            </Link>

            <nav>
              <ul className="flex gap-6 items-center">
                <li>
                  <Link href="/" className="hover:underline">
                    Home
                  </Link>
                </li>
                <li>
                  <Link href="/portfolio" className="hover:underline">
                    Portfolio
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="hover:underline">
                    About
                  </Link>
                </li>
                <li>
                  <Link href="/contact" className="hover:underline">
                    Contact
                  </Link>
                </li>
              </ul>
            </nav>
            <a className="px-4 py-2 bg-stone-800 text-[rgb(255,251,244)] font-im-fell-double-pica text-sm tracking-wide hover:bg-stone-700 transition-all duration-300 shadow-sm hover:shadow-md" href="https://docs.google.com/forms/d/e/1FAIpQLSc9BB6GobF0SZtveCfMxI4sGimjrXnBAqqGMti1itTiDctyKw/viewform"
              target="_blank">
                Book a Session
              </a>
          </div>

        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
